######################################################################
# Automatically generated by qmake (3.0) Thu Oct 5 23:36:31 2017
######################################################################

TEMPLATE = app
TARGET = hw2
INCLUDEPATH += .

# Input
HEADERS += QUtfStream.h
SOURCES += hw2.cpp QUtfStream.cpp
